name: movie-ci

on:
  push:
    branches: ['master']
    paths:
      - './**'

env:
  JWT_SECRET: xxxxxx
  PORT: 4000
  MONGODB_URI: mongodb://mongo_db:27017
  OMDB_URL:  http://www.omdbapi.com
  OMDB_API_KEY: 731280a1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd movie && npm install && npm test